Problem Statement 1:Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [2]:
import numpy as np
x = np.array([1,2,3,4])
def GEN_VAND(in1,N,Increasing):
    if Increasing:
        out = np.array([x**i for x in in1 for i in range(N)]).reshape(in1.size,N)
        
    else:
        out = np.array([x**(N-i-1) for x in in1 for i in range(N)]).reshape(in1.size,N)
        
    return out 
in1 = x
print(GEN_VAND(x,3,True))
print("-----------------")
print(GEN_VAND(x,3,False))

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]
-----------------
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.
-----------------------------------------------------------------------------------
Question:Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [12]:
import numpy as np
arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
def moving_average(arr,k):
    a = []
    for i in range(len(arr)- k + 1):
        sum1 = 0
        for j in range(i,i+k):
            sum1 = sum1 + arr[j]
        sum1 = sum1/3
        a.append(sum1)
    a = np.around(a, decimals = 2)
    print(a)
        
moving_average(arr,3)

[  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
